# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/InFE',
                'doc_host': 'https://chiaraf10.github.io',
                'git_url': 'https://github.com/chiaraf10/InFE',
                'lib_path': 'InFE'},
  'syms': { 'InFE.core': {'InFE.core.foo': ('segmentation.html#foo', 'InFE/core.py')},
            'InFE.segmentation': {'InFE.segmentation.foo': ('segmentation.html#foo', 'InFE/segmentation.py')}}}