# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/InFE',
                'doc_host': 'https://chiaraf10.github.io',
                'git_url': 'https://github.com/chiaraf10/InFE',
                'lib_path': 'InFE'},
  'syms': { 'InFE.core': {'InFE.core.foo': ('segmentation.html#foo', 'InFE/core.py')},
            'InFE.hello': { 'InFE.hello.HelloSayer': ('hello.html#hellosayer', 'InFE/hello.py'),
                            'InFE.hello.HelloSayer.__init__': ('hello.html#hellosayer.__init__', 'InFE/hello.py'),
                            'InFE.hello.HelloSayer.say': ('hello.html#hellosayer.say', 'InFE/hello.py'),
                            'InFE.hello.say_hello': ('hello.html#say_hello', 'InFE/hello.py')},
            'InFE.segmentation': {'InFE.segmentation.foo': ('segmentation.html#foo', 'InFE/segmentation.py')}}}