# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/1_hello.ipynb.

# %% auto 0
__all__ = ['say_hello']

# %% ../nbs/1_hello.ipynb 3
import pandas as pd
import numpy as np
import yaml
import os

# %% ../nbs/1_hello.ipynb 4
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'
